//DROP TABLE IF EXISTS GOODS_DETAIL;
//DROP TABLE IF EXISTS GOODS;
//DROP TABLE IF EXISTS CART;
//DROP TABLE IF EXISTS USER;
//DROP TABLE IF EXISTS AUTHORITES;

CREATE TABLE GOODS (
	GOODS_ID VARCHAR(200),
	GOODS_NM VARCHAR(40),
	PROVIDER VARCHAR(40),
	GOODS_PRICE INT(40),
	SHIPPING_ID VARCHAR(40),
	REG_ID VARCHAR(20),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	UPD_ID VARCHAR(20),
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (GOODS_ID)
);

CREATE TABLE SHIPPING (
	SHIPPING_ID VARCHAR(200),
	SHIPPING_PRICE INT(200),
	SHIPPING_CANBUNDLE VARCHAR(1),
	REG_ID VARCHAR(20),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	UPD_ID VARCHAR(20),
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (SHIPPING_ID)
);
  
CREATE TABLE GOODS_OPT (
	OPT_ID VARCHAR(200),
	GOODS_ID INT(10),
	COLOR VARCHAR(3), //COMM_CD : 001
	SIZE VARCHAR(3),  //COMM_CD : 000
	STOCK INT(100),    
	REG_ID VARCHAR(20),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPD_ID VARCHAR(20),
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID, GOODS_ID),
	FOREIGN KEY (GOODS_ID) REFERENCES GOODS (GOODS_ID)
);

//공통코드 사이즈 000 , 색상 001, 배송구분 002
CREATE TABLE COMM_CD (
	COMM_CD VARCHAR(3),
	COMM_NM VARCHAR(100),
	REG_ID VARCHAR(20),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	UPD_ID VARCHAR(20),
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (COMM_CD)
);

CREATE TABLE DT_CD (
	COMM_CD VARCHAR(3),
	DT_CD VARCHAR(3),
	COMM_NM VARCHAR(100),
	REG_ID VARCHAR(20),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	UPD_ID VARCHAR(20),
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (COMM_CD, DT_CD),
	FOREIGN KEY (COMM_CD) REFERENCES COMM_CD (COMM_CD)
);

 CREATE TABLE CART (
 	USER_ID VARCHAR(100),
	GOODS_ID INT(10),
	GOODS_DETAIL_ID INT(10),
	STOCK INT(10),
	REG_ID VARCHAR(20),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	UPD_ID VARCHAR(20),
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	FOREIGN KEY (GOODS_ID) REFERENCES GOODS (GOODS_ID)
 );
 
 CREATE TABLE USER (
 	USER_ID VARCHAR(100),
 	USER_NM VARCHAR(200),
 	EMAIL VARCHAR(40),
	USER_PWD VARCHAR(40),
	REG_ID VARCHAR(20),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	UPD_ID VARCHAR(20),
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (USER_ID),
 ); 
